apiVersion: v1
kind: Service
metadata:
  name: {{ include "automata.fullname" . }}
  labels:
    {{- include "automata.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "automata.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "automata.fullname" . }}-headless
  labels:
    {{- include "automata.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "automata.selectorLabels" . | nindent 4 }}
