[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:postgres]
command=/opt/all-in-one/scripts/start-postgres.sh
autostart=true
autorestart=true
startsecs=5
priority=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true

[program:temporal]
command=/opt/all-in-one/scripts/start-temporal.sh
autostart=true
autorestart=true
startsecs=5
priority=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true

[program:matrix]
command=/opt/all-in-one/scripts/start-matrix.sh
autostart=true
autorestart=true
startsecs=5
priority=30
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true

[program:matrix-provision]
command=/opt/all-in-one/scripts/provision-matrix.sh
autostart=true
autorestart=false
startsecs=0
priority=35
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true

[program:automata]
command=/opt/all-in-one/scripts/start-automata.sh
autostart=true
autorestart=true
startsecs=5
priority=40
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true

[program:element-web]
command=/opt/all-in-one/scripts/start-element-web.sh
autostart=true
autorestart=true
startsecs=5
priority=45
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
stopasgroup=true
killasgroup=true
